### ISSUE TITLE
Docker compose volumes settings

### ISSUE THREAD

**Issue by tntrex** [goldencodeio/carcass#16]
Add volumes section in docker-compose.prod.yml

Bitrix stack:
```yml
- shop_uploads:/var/www/html/upload
- shop_bx_core:/var/www/html/bitrix
```

Node stack:
```yml
- app_uploads:/home/node/www/public/uploads
```

Global volumes settings:
```yml
volumes:
  mongo_data:
    driver: vsphere
    driver_opts:
      size: 10gb
      fstype: xfs
```
